### ISSUE TITLE
Can't install since go.mod (v5.13+)

### ISSUE THREAD

**Issue by Korijn** [transip/gotransip#25]
For Go module libraries with major version >= 2, the major version is required to be part of the module path. See rules here: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

Since `v5` is not part of the URL for this library, I can't install it. I can only install versions of the library that predate your usage of `go.mod`, so the latest version available to me is `v5.8.2`.

I'm getting API errors (HTTP 500) running `domain.setDNSEntries` with that version of the library, though, so I'm kinda stuck at this point.

Any ideas?

# Reproduction

`go.mod`
```
module github.com/korijn/test

go 1.13

require (
	github.com/transip/gotransip v5.18.0
)
```

```
$ go mod download
go: finding github.com/transip/gotransip v5.18.0
go: finding github.com/transip/gotransip v5.18.0
go: errors parsing go.mod:
C:\Users\korij\dev\test\go.mod:7: require github.com/transip/gotransip: version "v5.18.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```

Leaving the entry out of `go.mod` and letting go pull in the library on its own when running `go build .` installs an outdated version:

```
github.com/transip/gotransip v5.8.2+incompatible // indirect
```

# Environment

```
$ go version
go version go1.13.1 windows/amd64
```

**Comment by skoef** [comment]
Hi @Korijn, thank you for bringing this issue to our attention. I think this is related to https://github.com/transip/gotransip/pull/20, on which we hadn't decide what to do with yet. Your issue makes this problem more severe so expect action in a short while.

**Comment by skoef** [comment]
This should be fixed nou, please confirm @Korijn

**Comment by Korijn** [comment]
Unfortunately, still having issues. Tried two things:

# Using the same go.mod file as before
```
module github.com/korijn/test

go 1.13

require (
	github.com/transip/gotransip v5.18.0
)
```

```
$ go build .
C:\Users\korij\dev\test\go.mod:7: require github.com/transip/gotransip: version "v5.18.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```

# After adding /v5 to go.mod
```
module github.com/korijn/test

go 1.13

require (
	github.com/transip/gotransip/v5 v5.18.0
)
```

```
$ go build .
go: github.com/transip/gotransip/v5@v5.18.0: go.mod has non-.../v5 module path "github.com/transip/gotransip" (and .../v5/go.mod does not exist) at revision v5.18.0
```

**Comment by skoef** [comment]
Indeed I haven't tagged a new version, but what could work is to create a go.mod like this:

```
module github.com/korijn/test

go 1.13

require (
	github.com/transip/gotransip/v5 v5.18.0
)

replace github.com/transip/gotransip/v5 => /path/to/local/checkout/of/the/repo
```
This builds fine and if I remove the `replace` line I get the same error you do. I'll tag a new version but it will be `v5.18.1` and not `v5.19.0` as we're following the TransIP PHP API client version which is still at `v5.18`.

**Comment by Korijn** [comment]
I was not aware of go.mod's `replace` syntax, that did the trick. The new release v5.18.1 installs without problems! Thanks!
